type Auth = {
  emailId: string;
  auth_token: string;
  id: number;
  fullName?: string;
  // parkingManager: {
  //   id: number;
  //   name: string;
  //   active: boolean;
  //   createdAt: string | Date;
  //   deactive: boolean;
  //   email?: string | null;
  //   firstName?: string;
  //   lastName?: string;
  //   mobileNumber: string;
  //   parkingSpotId: number;
  //   parkingSpot: {
  //     active: boolean;
  //     address?: string | number;
  //     area?: string | number;
  //     city?: string | number;
  //     closeTime?: string | number;
  //     companyActive: boolean;
  //     coordinate?: string | number;
  //     country?: string | number;
  //     createdAt?: string | number;
  //     deactive: boolean;
  //     exhibitionActive: boolean;
  //     fourWheelerActive: boolean;
  //     fourWheelerBuffer?: number;
  //     geoLocation?: string | number;
  //     hmvActive: boolean;
  //     hmvBuffer?: number;
  //     id: number;
  //     landmark?: string | number;
  //     nevon: boolean;
  //     openTime?: string | number;
  //     parkingSpotCode?: string | number;
  //     parkingSpotName?: string;
  //     parkingSpotPicture?: string | number;
  //     prepaidFourWheeler: boolean;
  //     prepaidHmv: boolean;
  //     prepaidThreeWheeler: boolean;
  //     prepaidTwoWheeler: boolean;
  //     pricingCategory?: string | number;
  //     showVendorName: boolean;
  //     state?: string | number;
  //     threeWheelerActive: boolean;
  //     threeWheelerBuffer?: number;
  //     totalNumberFourWheeler?: number;
  //     totalNumberHMV?: string | number;
  //     totalNumberThreeWheeler?: string | number;
  //     totalNumberTwoWheeler?: string | number;
  //     twoWheelerActive: boolean;
  //     twoWheelerBuffer?: number;
  //     updatedAt?: string | number;
  //   };
  // };
};
